# -*- coding: utf-8 -*-
"""Text2Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mOqmaaUi7VmrCa1arRxcDTqEoX2nIqO5
"""

import streamlit as st
import requests
import base64
from PIL import Image

API_URL = "https://api-inference.huggingface.co/models/impira/layoutlm-document-qa"
headers = {"Authorization": "Bearer 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"}

def query(payload):
    with open(payload["image"], "rb") as f:
        img = f.read()
        payload["image"] = base64.b64encode(img).decode("utf-8")
    response = requests.post(API_URL, headers=headers, json=payload)
    return response.json()

def image_to_text_with_layoutlm(image_path, question):
    payload = {
        "inputs": {
            "image": image_path,
            "question": question
        }
    }
    output = query(payload)
    return output

def main():
    st.title("Document Q&A with LayoutLM")

    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
    question = st.text_input("Enter a question about the image:")

    if uploaded_file is not None and question:
        # Display the selected image
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image", use_column_width=True)

        # Perform image to text conversion with LayoutLM Document QA
        if st.button("Convert Image to Text"):
            result = image_to_text_with_layoutlm(uploaded_file.name, question)
            st.subheader("Text Extracted:")
            st.write(result)

if __name__ == "__main__":
    main()